ycsite/users/urls.py
from django.urls import path ,re_path,register_converter

from users.views import users_list, users_detail

from . import views

class FourDigitYearConverter:
    regex = '[0-9]{4}'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%04d' % value

register_converter(FourDigitYearConverter, 'yyyy')
app_name = "users"

urlpatterns = [
    path('user_l/<path:uid>',views.users_list, name="usersCharge"),
    path('user_lis/<path:uid>',views.users_list, name="usersList"),
    path('user_li/<path:uid>',views.users_list, name="usersDetail"),
    # path('users_list/',views.users_list, name="usersList"),
    path('<int:uid>/', views.users_detail),
    # path('users/<int:uid>/', users_detail),
    # path('users/<slug:uid>/', users_detail),
    # path('users/<slug:name>/', users_list),
    # path('users/<yyyy:uid>/', users_detail),
    # re_path(r'^(?P<uid>\w+)/$',views.users_detail,name="users_detail"),
    # re_path(r'^users/(?P<name>\w+)/$',users_list)
]

ycsite/ycsite/urls.py
from django.contrib import admin
from django.urls import path,include,register_converter,re_path
from users.views import users_list, users_detail
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/',include('users.urls'))
    # 访问 /users/
]     

ycsite/users/models.py
from django.db import models

# Create your models here.

ycsite/users/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def users_list(request,uid):
    username = uid
    return HttpResponse(f"{username}")



# def users_detail(request,uid):
#     # 去数据库取到 id 为uid 的用户数据，并返回
#     # print(type(uid))
#     return HttpResponse(f"{uid}")


def users_detail(request, uid):
    return render(request,
    "base2的副本.html",             # 要连接的HTML文件名
    context={"userinfo": uid})     # 将所接受到的参数传进文件

ycsite/ycsite/views.py
from django.shortcuts import reverse
def index(request):
    return reverse(request, 'index')

ycsite/templates/base2的副本.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/Users/mac/Desktop/task/yicheng/day19/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <!-- 设置页面的标题栏图标 -->
    <link rel="shortcut icon" href="/Users/mac/Desktop/task/yicheng/day19/ding.jpg">
    <!-- 设置页面的标题 -->
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <script src="/Users/mac/Desktop/task/yicheng/day21/jQuery.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <style>
        .naver {
            width: 20%;
            height: 20%;
        }
    </style>
</head>

<body>

    <head>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Brand</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">警报</a></li>
                        <li class="active1"><a href="#">邮件</a></li>
                        <li class="dropdown">
                            <!-- 含有下级菜单的第一级菜单设置 -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                aria-haspopup="true" aria-expanded="false">
                                <img src="/Users/mac/Desktop/task/yicheng/day19/ding.jpg" alt="头像" class="img-circle naver">
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人中心</a></li>
                                <li><a href="#">修改头像</a></li>
                                <li><a href="#">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">退出</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </head>

    <!--section 设置 class"row"设置内容大小 -->
    <section class="row">
        <!-- 设置内容所占页面比例 -->
        <div class="col-md-2">
            <ul class="nav aside nav-pills nav-stacked nav-pills-stacked-example">
                <!--ul 菜单 li 同级列表  ol 多级列表  -->
                <li role="presentation" class="active"><a href="#">Home</a></li>
                <li role="presentation"><a href="#">资产信息
                        <span class="glyphicon glyphicon-plus navbar-right"></span>
                    </a>
                    <ul class="nav nav-pills nav-stacked nav-pills-stacked-example">
                        <li role="presentation"><a href="#">资产列表</a></li>
                        <li role="presentation"><a href="#">修改资产信息</a></li>
                        <li role="presentation"><a href="#">添加资产信息</a></li>
                    </ul>
                </li>
                <li role="presentation"><a href="#">服务器信息
                        <span class="glyphicon glyphicon-plus navbar-right"></span>
                    </a>
                    <ul class="nav  nav-pills nav-stacked nav-pills-stacked-example">
                        <li role="presentation"><a href="#">服务器资产列表</a></li>
                        <li role="presentation"><a href="#">服务器资产信息</a></li>
                        <li role="presentation"><a href="#">服务器资产信息</a></li>
                    </ul>
                </li>
                <li role="presentation">
                    <a href="{% url 'users:usersCharge' 6576 %}">用户管理
                        <span class="glyphicon glyphicon-plus navbar-right"></span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'users:usersList' 213 %}">用户列表</a>
                </li>
                <li role="presentation">
                    <a href="{% url 'users:usersDetail' 434 %}">用户详情</a>
                </li>


            </ul>
        </div>
        <div class="col-md-10"> asdsd
            <div class="row">
                <div class="col-md-2">
                    <button id="nv" class="btn btn-success"> 请确认</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6" id="p">
                    <p>p1</p>
                    <p class="url">p2</p>
                    <p>p3</p>
                    <!-- label 中 for 的值必须和 input 的 id 的值相同 -->
                    <label for="inputusername">用户名</label>
                    <input type="text" name="username" id="inputusername" class="form-control" value="yangge"
                        required="required" pattern="" title="">
                </div>
            </div>
            <div class="col-md-6">


            </div>
            <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Column heading</th>
                            <th>Column heading</th>
                            <th>Column heading</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="active">
                            <th scope="row">1</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr class="success">
                            <th scope="row">3</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr>
                            <th scope="row">4</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr class="info">
                            <th scope="row">5</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr>
                            <th scope="row">6</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr class="warning">
                            <th scope="row">7</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr>
                            <th scope="row">8</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                        <tr class="danger">
                            <th scope="row">9</th>
                            <td>Column content</td>
                            <td>Column content</td>
                            <td>Column content</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

</body>

<!-- 进入页面时弹出对话框 script -->
<!-- <script> -->
<!-- // 单次定时器
    // setTimeout(
    //     function () {
    //         alert("中秋愉快，要吃肉，吃肉就长胖");
    //     },5000
    // )

    // 多次定时器
    // $(".sloter>li").on("click", function () {
    //     $(document).ready(function () {
    //         // 移除自己的兄弟标签的类名 active
    //         $(this).siblings().remove("active")
    //         // 给自己添加一个类名 active
    //         $(this).addClass("active")
    //     });
    // }) -->
<!-- </script> -->

<script src="/Users/mac/Desktop/task/yicheng/day21/jQuery.js"></script>
<script type="text/JavaScript">
    $(function(){
        var aside_active_tag = $(".aside>li.active")
        aside_active_tag.siblings().children("ul").attr("hidden",true);
        let aside_tag = $(".aside>li") 
        aside_tag.on("click",function(){
         // 移除自己的兄弟标签的类名 active
        $(this).siblings().removeClass("active");
        // 给自己添加一个类名 active
        $(this).addClass("active");
        // 让自己兄弟标签的所有子标签中的ul标签隐藏
        $(this).siblings().children("ul").attr("hidden",true);
        // 让自己的所有子标签中的ul显示
        $(this).children("ul").attr("hidden",false);
        // 添加移除字体图标
        $(this).siblings().children("a").children().attr("class","glyphicon glyphicon-plus navbar-right")
        $(this).children("a").children().attr("class","glyphicon glyphicon-menu-down navbar-right")
        // $(this).siblings().children('a').children().removeClass("glyphicon glyphicon-plus");
        // $(this).siblings().children('a').children().addClass("glyphicon glyphicon-menu-down");
        // $(this).children("a").children().removeClass("glyphicon-menu-down");
        // $(this).children("a").children().addClass("glyphicon glyphicon-plusglyphicon");

    })
})
    let btn = document.getElementById("nv")
    let msg = ["hello", "world", "中秋愉快"]
    current_msg = false
    function func() {
        if (!current_msg) {
            current_msg = msg;
        }
        btn.innerText = current_msg[0];
        var w = current_msg.shift();
        current_msg.push(w)
    }
    timer = setInterval(function () {
        func()
    }, 2000
    );
    alert("hello javascript")

    // let ask = confirm("20k 要不要");
    // let btn = ducument.getElementByID("nv")
    // if (ask){
    //     btn.innerText = "已确认";
    // }else if(ask){
    //     btn.innerText = "已取消";
    // }
    // s = "Hello 好程序员"
    // alert(s)
    // console.log(s)
    // // 匿名函数  传参
    // function foo(arg){
    //     arg()
    // }
    // // 匿名函数 foo()传进去的参数为匿名函数
    // foo(
    //     function(){
    //         console.log('ok')
    //     }
    // )
</script>

</html>

ycsite/templates/users_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>用户详情页面</title>
</head>
<body>
    <div>{{ userinfo }}</div>
    <!-- <a href="/users/users_list/">用户列表</a> -->
    <a href="{% url 'users:usersList' %}">用户列表</a>
</body>
</html>